# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Tempo Utility’ do

pod "LGBluetooth", "~> 1.1.5"
pod 'MBProgressHUD', '~> 0.9'
pod 'CorePlot', '~> 2.0'

end

